Repository ubc-minetest-classroom/minetest_classroom, pull requests merged in 2022-05, with the labels that each got.

#8 Add magnifying glass prototype
  mods/magnify/init.lua
  mods/magnify/mod.conf
  mods/magnify/textures/magnifying_tool.png
  mods/magnify/textures/test.png
  mods/mc_teacher/gui_dash.lua
  mods/unbreakable_map_barrier/.gitignore
  mods/unbreakable_map_barrier/init.lua
  mods/unbreakable_map_barrier/textures/.gitignore
  mods/unbreakable_map_barrier/textures/default_glass.png
  mods/unbreakable_map_barrier/textures/default_glass_detail.png
Labels: Feature

#12 Custom magnifying glass tool, plant compendium, and teacher menu redesign
  mods/magnify/exports.lua
  mods/magnify/init.lua
  mods/magnify_default_nodes/init.lua
  mods/magnify_default_nodes/mod.conf
  mods/magnify_default_nodes/textures/test.png
  mods/magnify_flowers_nodes/ATTRIBUTIONS.md
  mods/magnify_flowers_nodes/init.lua
  mods/magnify_flowers_nodes/mod.conf
  mods/magnify_flowers_nodes/textures/1280px-California_poppies_open.jpg
  mods/magnify_flowers_nodes/textures/Anapahlis_margaritacea.jpg
  mods/magnify_flowers_nodes/textures/Castilleja_miniata_var._miniata.jpg
  mods/magnify_flowers_nodes/textures/Eschscholzia.jpg
  mods/magnify_flowers_nodes/textures/Trifolium_cyathiferum.jpg
  mods/magnify_flowers_nodes/textures/fritillaria-affinis.jpg
  mods/mc_teacher/gui_dash.lua
  mods/mc_teacher/mod.conf
Labels: Feature

#22 Removed "pointable" from the barrier node
  mods/unbreakable_map_barrier/init.lua
Labels: Feature

#20 Patch/portal fix
  mods/mc_realmportals/init.lua
  mods/mc_realmportals/portalhelper.lua
  mods/mc_tutorial_framework/init.lua
  mods/mc_tutorial_framework/mod.conf
  mods/mc_tutorial_framework/realmTemplates/TestSchematic.conf
  mods/mc_tutorial_framework/realmTemplates/TestSchematic.mts
  mods/mc_worldmanager/commands.lua
  mods/mc_worldmanager/init.lua
  mods/mc_worldmanager/realm.lua
  mods/mc_worldmanager/schematicmanager.lua
  mods/mc_worldmanager/schematics/shack.conf
Labels: bug

#28 Refactor tool registration + give/take handing
  mods/magnify/init.lua
  mods/magnify/mod.conf
  mods/mc_helpers/init.lua
  mods/mc_helpers/mod.conf
  mods/mc_student/init.lua
  mods/mc_student/mod.conf
  mods/mc_teacher/gui_dash.lua
  mods/mc_teacher/init.lua
  mods/mc_teacher/mod.conf
Labels: question

#29 Magnify tool improvements + additional plant data
  README.md
  mods/magnify/api.lua
  mods/magnify/exports.lua
  mods/magnify/init.lua
  mods/magnify/mod.conf
  mods/magnify/models/.gitignore
  mods/magnify/models/acacia_tree.obj
  mods/magnify/models/apple_tree.obj
  mods/magnify/models/aspen_tree.obj
  mods/magnify/models/jungle_tree.obj
  mods/magnify/models/pine_tree.obj
  mods/magnify_default_nodes/ATTRIBUTIONS.md
  mods/magnify_default_nodes/init.lua
  mods/magnify_default_nodes/models/.gitignore
  mods/magnify_default_nodes/models/acacia_tree.obj
  mods/magnify_default_nodes/models/apple_tree.obj
  mods/magnify_default_nodes/models/aspen_tree.obj
  mods/magnify_default_nodes/models/jungle_tree.obj
  mods/magnify_default_nodes/models/pine_tree.obj
  mods/magnify_default_nodes/models/tree_test.obj
  mods/magnify_default_nodes/textures/1290859805_c0f741fe00_o.jpg
  mods/magnify_default_nodes/textures/4691167139_41c8a71b20_o.jpg
  mods/magnify_default_nodes/textures/Malus_fusca.jpg
  mods/magnify_default_nodes/textures/Physocarpus_capitatus_18343.jpg
  mods/magnify_default_nodes/textures/Pinus_contorta_28266.jpg
  mods/magnify_default_nodes/textures/Populus_tremuloides_02.jpg
  mods/magnify_default_nodes/textures/Vacciniumovatum.jpg
  mods/magnify_default_nodes/textures/struthiopteris-spicant-1.jpg
  mods/magnify_default_nodes/textures/test.png
  mods/magnify_flowers_nodes/ATTRIBUTIONS.md
  mods/magnify_flowers_nodes/init.lua
  mods/magnify_flowers_nodes/textures/1280px-California_poppies_open.jpg
  mods/mc_helpers/init.lua
  mods/mc_student/init.lua
  mods/mc_student/mod.conf
  mods/mc_teacher/gui_dash.lua
  mods/mc_teacher/mod.conf
Labels: Feature
