Repository ubc-minetest-classroom/minetest_classroom, pull requests merged in 2022-06, with the labels that each got.

#72 Fix node destruction on drop attempt
  mods/magnify/init.lua
  mods/mc_student/init.lua
  mods/mc_teacher/gui_dash.lua
  mods/mc_teacher/init_old.lua
  mods/mc_tutorial_framework/init.lua
Labels: bug

#74 Toolbox + tool handling refactor
  mods/magnify/magnify/init.lua
  mods/mc_helpers/init.lua
  mods/mc_student/init.lua
  mods/mc_teacher/gui_dash.lua
  mods/mc_toolhandler/init.lua
  mods/mc_toolhandler/mod.conf
  mods/mc_toolmenu/init.lua
  mods/mc_toolmenu/mod.conf
  mods/mc_tutorial_framework/init.lua
Labels: Feature

#90 Patch/lua5.0 workaround
  mods/mc_worldmanager/commands.lua
  mods/mc_worldmanager/realm/realm.lua
Labels: bug

#102 Polish up `magnify` mod + fully decouple `magnify` from `mc_helpers`
  mods/magnify/magnify/README.md
  mods/magnify/magnify/api.lua
  mods/magnify/magnify/init.lua
  mods/mc_helpers/init.lua
Labels: bug, Feature

#96 Improve `mc_toolhandler` mod + make toolbox dynamically scalable
  mods/magnify/magnify/init.lua
  mods/mc_student/init.lua
  mods/mc_teacher/gui_dash.lua
  mods/mc_toolhandler/README.md
  mods/mc_toolhandler/init.lua
  mods/mc_toolhandler/mod.conf
  mods/mc_toolmenu/init.lua
  mods/mc_tutorial_framework/init.lua
Labels: Feature

#103 Prevent managed tools from being taken out of player inventory
  mods/mc_toolhandler/README.md
  mods/mc_toolhandler/init.lua
Labels: Feature

#107 Complete implementation of `mc_toolhandler`
  mods/mc_toolhandler/README.md
  mods/mc_toolhandler/api.lua
  mods/mc_toolhandler/init.lua
  mods/mc_toolhandler/textures/mc_toolhandler_test_store.png
Labels: Feature
